services:
  backend:
    build:
      context: ./server
    container_name: tracker-backend
    depends_on:
    - mqtt
    - postgres
    environment:
    - DB_BACKEND=postgres
    - DATABASE_URL=postgresql://gps:gps_pw_2024@postgres:5432/gps
    - DB_PATH=/app/data/tracker.db
    - MQTT_BROKER=mqtt
    - MQTT_PORT=1883
    - ADMIN_SECRET=3e9651d4d2bd074817f5b868ae875b9719d63d1a08a653a2
    - PORTAL_SECRET=81abeed060162179e4fa857bfc07f2258de64e0e8302ee94
    - MQTT_USER=gps_device
    - MQTT_PASS=zYMxS+K4KZnPa7cgypQeDg==
    ports:
    - 9090:9090
    restart: unless-stopped
    volumes:
    - tracker_data:/app/data
  frontend:
    build:
      context: ./frontend
    container_name: tracker-frontend
    depends_on:
    - backend
    ports:
    - 80:80
    restart: unless-stopped
  mqtt:
    container_name: tracker-mqtt
    image: eclipse-mosquitto:2
    ports:
    - 1883:1883
    - 9001:9001
    restart: unless-stopped
    volumes:
    - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    - ./passwd:/mosquitto/config/passwd:ro
  postgres:
    container_name: tracker-postgres
    environment:
    - POSTGRES_USER=gps
    - POSTGRES_PASSWORD=gps_pw_2024
    - POSTGRES_DB=gps
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
    - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
    driver: local
  tracker_data:
    driver: local
