# Mosquitto MQTT Broker (Auth Enabled)
password_file /mosquitto/config/passwd
allow_anonymous false

# TCP Listener
listener 1883

# WebSocket Listener
listener 9001
protocol websockets
password_file /mosquitto/config/passwd
allow_anonymous false

# Logging
log_type error
log_type warning
log_type information
